// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: student_info.proto

package student_info

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for StudentService service

type StudentService interface {
	SetStudentInfo(ctx context.Context, in *SetStudentInfoReq, opts ...client.CallOption) (*SetStudentInfoRsp, error)
	GetStudentInfo(ctx context.Context, in *GetStudentInfoReq, opts ...client.CallOption) (*GetStudentInfoRsp, error)
}

type studentService struct {
	c    client.Client
	name string
}

func NewStudentService(name string, c client.Client) StudentService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "studentservice"
	}
	return &studentService{
		c:    c,
		name: name,
	}
}

func (c *studentService) SetStudentInfo(ctx context.Context, in *SetStudentInfoReq, opts ...client.CallOption) (*SetStudentInfoRsp, error) {
	req := c.c.NewRequest(c.name, "StudentService.SetStudentInfo", in)
	out := new(SetStudentInfoRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentService) GetStudentInfo(ctx context.Context, in *GetStudentInfoReq, opts ...client.CallOption) (*GetStudentInfoRsp, error) {
	req := c.c.NewRequest(c.name, "StudentService.GetStudentInfo", in)
	out := new(GetStudentInfoRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StudentService service

type StudentServiceHandler interface {
	SetStudentInfo(context.Context, *SetStudentInfoReq, *SetStudentInfoRsp) error
	GetStudentInfo(context.Context, *GetStudentInfoReq, *GetStudentInfoRsp) error
}

func RegisterStudentServiceHandler(s server.Server, hdlr StudentServiceHandler, opts ...server.HandlerOption) error {
	type studentService interface {
		SetStudentInfo(ctx context.Context, in *SetStudentInfoReq, out *SetStudentInfoRsp) error
		GetStudentInfo(ctx context.Context, in *GetStudentInfoReq, out *GetStudentInfoRsp) error
	}
	type StudentService struct {
		studentService
	}
	h := &studentServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&StudentService{h}, opts...))
}

type studentServiceHandler struct {
	StudentServiceHandler
}

func (h *studentServiceHandler) SetStudentInfo(ctx context.Context, in *SetStudentInfoReq, out *SetStudentInfoRsp) error {
	return h.StudentServiceHandler.SetStudentInfo(ctx, in, out)
}

func (h *studentServiceHandler) GetStudentInfo(ctx context.Context, in *GetStudentInfoReq, out *GetStudentInfoRsp) error {
	return h.StudentServiceHandler.GetStudentInfo(ctx, in, out)
}
