// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student_info.proto

package student_info

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetStudentInfoReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  string   `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  string   `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	MathScore            string   `protobuf:"bytes,4,opt,name=mathScore,proto3" json:"mathScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStudentInfoReq) Reset()         { *m = SetStudentInfoReq{} }
func (m *SetStudentInfoReq) String() string { return proto.CompactTextString(m) }
func (*SetStudentInfoReq) ProtoMessage()    {}
func (*SetStudentInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dd1e75146a81ea4, []int{0}
}

func (m *SetStudentInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStudentInfoReq.Unmarshal(m, b)
}
func (m *SetStudentInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStudentInfoReq.Marshal(b, m, deterministic)
}
func (m *SetStudentInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStudentInfoReq.Merge(m, src)
}
func (m *SetStudentInfoReq) XXX_Size() int {
	return xxx_messageInfo_SetStudentInfoReq.Size(m)
}
func (m *SetStudentInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStudentInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetStudentInfoReq proto.InternalMessageInfo

func (m *SetStudentInfoReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetStudentInfoReq) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *SetStudentInfoReq) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *SetStudentInfoReq) GetMathScore() string {
	if m != nil {
		return m.MathScore
	}
	return ""
}

type SetStudentInfoRsp struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  string   `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  string   `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	MathScore            string   `protobuf:"bytes,4,opt,name=mathScore,proto3" json:"mathScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStudentInfoRsp) Reset()         { *m = SetStudentInfoRsp{} }
func (m *SetStudentInfoRsp) String() string { return proto.CompactTextString(m) }
func (*SetStudentInfoRsp) ProtoMessage()    {}
func (*SetStudentInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dd1e75146a81ea4, []int{1}
}

func (m *SetStudentInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStudentInfoRsp.Unmarshal(m, b)
}
func (m *SetStudentInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStudentInfoRsp.Marshal(b, m, deterministic)
}
func (m *SetStudentInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStudentInfoRsp.Merge(m, src)
}
func (m *SetStudentInfoRsp) XXX_Size() int {
	return xxx_messageInfo_SetStudentInfoRsp.Size(m)
}
func (m *SetStudentInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStudentInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SetStudentInfoRsp proto.InternalMessageInfo

func (m *SetStudentInfoRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetStudentInfoRsp) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *SetStudentInfoRsp) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *SetStudentInfoRsp) GetMathScore() string {
	if m != nil {
		return m.MathScore
	}
	return ""
}

type GetStudentInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStudentInfoReq) Reset()         { *m = GetStudentInfoReq{} }
func (m *GetStudentInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetStudentInfoReq) ProtoMessage()    {}
func (*GetStudentInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dd1e75146a81ea4, []int{2}
}

func (m *GetStudentInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudentInfoReq.Unmarshal(m, b)
}
func (m *GetStudentInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudentInfoReq.Marshal(b, m, deterministic)
}
func (m *GetStudentInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentInfoReq.Merge(m, src)
}
func (m *GetStudentInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetStudentInfoReq.Size(m)
}
func (m *GetStudentInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentInfoReq proto.InternalMessageInfo

type GetStudentInfoRsp struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  string   `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  string   `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	MathScore            string   `protobuf:"bytes,4,opt,name=mathScore,proto3" json:"mathScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStudentInfoRsp) Reset()         { *m = GetStudentInfoRsp{} }
func (m *GetStudentInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetStudentInfoRsp) ProtoMessage()    {}
func (*GetStudentInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dd1e75146a81ea4, []int{3}
}

func (m *GetStudentInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudentInfoRsp.Unmarshal(m, b)
}
func (m *GetStudentInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudentInfoRsp.Marshal(b, m, deterministic)
}
func (m *GetStudentInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentInfoRsp.Merge(m, src)
}
func (m *GetStudentInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetStudentInfoRsp.Size(m)
}
func (m *GetStudentInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentInfoRsp proto.InternalMessageInfo

func (m *GetStudentInfoRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetStudentInfoRsp) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *GetStudentInfoRsp) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *GetStudentInfoRsp) GetMathScore() string {
	if m != nil {
		return m.MathScore
	}
	return ""
}

func init() {
	proto.RegisterType((*SetStudentInfoReq)(nil), "SetStudentInfoReq")
	proto.RegisterType((*SetStudentInfoRsp)(nil), "SetStudentInfoRsp")
	proto.RegisterType((*GetStudentInfoReq)(nil), "GetStudentInfoReq")
	proto.RegisterType((*GetStudentInfoRsp)(nil), "GetStudentInfoRsp")
}

func init() { proto.RegisterFile("student_info.proto", fileDescriptor_8dd1e75146a81ea4) }

var fileDescriptor_8dd1e75146a81ea4 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x2e, 0x29, 0x4d,
	0x49, 0xcd, 0x2b, 0x89, 0xcf, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xca,
	0xe4, 0x12, 0x0c, 0x4e, 0x2d, 0x09, 0x86, 0x48, 0x78, 0xe6, 0xa5, 0xe5, 0x07, 0xa5, 0x16, 0x0a,
	0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9,
	0x42, 0x02, 0x5c, 0xcc, 0x89, 0xe9, 0xa9, 0x12, 0x4c, 0x60, 0x21, 0x10, 0x13, 0x24, 0x52, 0x9c,
	0x5a, 0x21, 0xc1, 0x0c, 0x11, 0x29, 0x4e, 0xad, 0x10, 0x92, 0xe1, 0xe2, 0xcc, 0x4d, 0x2c, 0xc9,
	0x08, 0x4e, 0xce, 0x2f, 0x4a, 0x95, 0x60, 0x01, 0x8b, 0x23, 0x04, 0xb0, 0x58, 0x55, 0x5c, 0x40,
	0x23, 0xab, 0x84, 0xb9, 0x04, 0xdd, 0xd1, 0x7d, 0x05, 0xb2, 0xdf, 0x9d, 0x3e, 0xf6, 0x1b, 0x75,
	0x30, 0x72, 0xf1, 0x41, 0x2d, 0x0a, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xb2, 0xe2, 0xe2,
	0x43, 0xf5, 0xbd, 0x90, 0x90, 0x1e, 0x46, 0xc8, 0x4b, 0x61, 0x88, 0x15, 0x17, 0x28, 0x31, 0x80,
	0xf4, 0xba, 0xa3, 0xeb, 0x75, 0xc7, 0xa2, 0xd7, 0x1d, 0x53, 0x6f, 0x12, 0x1b, 0x38, 0x9e, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0x6f, 0xe4, 0x4e, 0xfd, 0x01, 0x00, 0x00,
}
